### ISSUE TITLE
Dashboard creation fails with v0.10.1: "could not get configJSON: spec.forProvider.configJSON: no such field"

### ISSUE THREAD

**Issue by patst** [grafana/crossplane-provider-grafana#89]
After updating to provider version 'v0.10.1' Dashboard creation no longer works.

The error is probably related to https://github.com/grafana/crossplane-provider-grafana/blob/c4b592aefd9223ec9ef44a8161226d0b65c6048b/config/grafana/dashboard_init.go#L32  introduced by https://github.com/grafana/crossplane-provider-grafana/pull/86 

Message:
`  ----     ------                           ----                ----                                                        -------
  Warning  CannotInitializeManagedResource  59s (x9 over 4m2s)  managed/oss.grafana.crossplane.io/v1alpha1, kind=dashboard  could not get configJSON: spec.forProvider.configJSON: no such field
`

The field in the CRD is `spec.forProvider.configJson` (lower cased 'son', see https://github.com/grafana/crossplane-provider-grafana/blob/c4b592aefd9223ec9ef44a8161226d0b65c6048b/apis/oss/v1alpha1/zz_dashboard_types.go#L70).

**Comment by julienduchesne** [comment]
Yep, sorry about that. I'm fixing it right now

**Comment by julienduchesne** [comment]
I should definitely get some integration tests going. I'll look into uptest

**Comment by julienduchesne** [comment]
This is fixed in v0.10.2. I deployed it on our clusters, and it's applying dashboards correctly now
