### PR TITLE
fix(deps): update terraform-provider-grafana to v4.39.0

### PR DESCRIPTION
**Pull request by Duologic**
## Summary

Bumps `github.com/grafana/terraform-provider-grafana/v4` to **v4.39.0**, working around the k8s.io version conflict from #601 by pinning the k8s.io stack to v0.35.

## Background

v4.39.0 pulls in the **k8s.io v0.36** stack (via `grafana-app-sdk` v0.56.0 and `grafana/apps/provisioning`). client-go v0.36 added `HasSyncedChecker()` to `cache.ResourceEventHandlerRegistration`, which the **controller-runtime v0.22** pinned by crossplane-runtime v2.1.x does not implement — this is what broke `make generate` in #601.

The clean fix (controller-runtime v0.24) is still blocked upstream:
- crossplane-runtime [#1037](https://github.com/crossplane/crossplane-runtime/pull/1037) (controller-runtime v0.24 / client-go v0.36) — open, CI failing
- upjet [#664](https://github.com/crossplane/upjet/pull/664) (apis/common migration) — open, awaiting review

## Approach

The k8s.io modules are a co-versioned set and cannot straddle v0.35/v0.36 individually (client-go v0.35's scheme imports API groups removed in v0.36; apiserver v0.36 imports apimachinery packages added in v0.36). So this pins the **entire k8s.io stack** back to v0.35.3 as a matched set via `replace` directives:

- `k8s.io/api`, `apimachinery`, `apiserver`, `apiextensions-apiserver`, `client-go`, `code-generator`, `component-base` → v0.35.3

This keeps the module graph compatible with the currently-pinned controller-runtime v0.22 while adopting the v4.39.0 provider schema.

## Verification

- `go build ./...` — passes
- `go vet ./...` — passes
- The `upjet` + `controller-runtime/pkg/cache` packages that produced the original `HasSyncedChecker` error now compile

## Follow-up

The `replace` block is a temporary workaround. It should be removed once crossplane-runtime ships a release combining v2.3.x with controller-runtime v0.24 and the grafana upjet fork adopts it.

Refs #601

### CODE REVIEW

File: go.mod [hunk 1]
```diff
@@ -230,24 +235,42 @@ require (
...
+// See https://github.com/grafana/crossplane-provider-grafana/issues/601.
+replace (
+	k8s.io/api => k8s.io/api v0.35.3
+	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.35.3
+	k8s.io/apimachinery => k8s.io/apimachinery v0.35.3
+	k8s.io/apiserver => k8s.io/apiserver v0.35.3
+	k8s.io/client-go => k8s.io/client-go v0.35.3
+	k8s.io/code-generator => k8s.io/code-generator v0.35.3
+	k8s.io/component-base => k8s.io/component-base v0.35.3
+)
```
Comment (Duologic) [inline go.mod:276]: Note this block for review specifically, see comment for details.

**Comment by Duologic** [comment]
Superseded by #617, which now carries the same k8s.io v0.35 pin + regenerated code on the newer v4.39.1. Closing in favor of that.
